language: go
go:
  - 1.13.8
  - master
  - tip

os:
  - linux
  - osx
  - windows

script:
  - go test ./pkg
  - go test ./internal/blockchain ./internal/persistence ./internal/cli
  - go build cmd/cli/main.go
